modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/palaster/Get-A-Job/issues"
[[mods]]
modId="gj"
version="${file.jarVersion}"
displayName="Get-A-Job"
updateJSONURL="https://raw.githubusercontent.com/palaster/Get-A-Job/master/version/update.json"
#logoFile="gj.png"
authors="Palaster"
description='''
Get A Job. Get a job in magical or non-magical career.
'''
[[dependencies.gj]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gj]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
